services:
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
  clickhouse:
    image: clickhouse/clickhouse-server:23.8.14.6
    ports:
      - 8123:8123
      - 9002:9000
    environment:
      - CLICKHOUSE_PASSWORD=dev_password_only
    
