name: Build & Push Climate Mediator image

on:
  push:
    tags:
      - "*.*.*"
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: npm run build

      - name: Build and push tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jembi/climate-mediator:${{ github.ref_name }}

      - name: Build and push latest
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jembi/climate-mediator:latest