name: Scan latest climate mediator image

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  scan-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t jembi/climate-mediator:${{ github.sha }} .

      - name: Run trivy vulnerability scanner for the climate mediator image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/climate-mediator:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
        
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'