name: Run Climate Mediator Tests
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      # Start Docker Compose services
      - name: Start services with Docker Compose
        run: docker compose up clickhouse -d
      
      - name: Run tests
        run: NODE_ENV=test npm run test
      
      - name: Tear down services
        if: always()
        run: docker compose down
