name: Run Climate Mediator Tests
on:
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v3

      # Start Docker Compose services
      - name: Start services with Docker Compose
        run: docker compose up -d
      
      - name: Run tests
        run: npm run test
      
      - name: Tear down services
        if: always()
        run: docker compose down
